### PR TITLE
Add chocolatey

### LINKED ISSUE #28: Suggestion: Make a Chocolatey install package
Would you mind, if I create a package for https://chocolatey.org/ ?

### PR DESCRIPTION
**Pull request by RufusJWB**
Fixes https://github.com/NoMoreFood/putty-cac/issues/28

### CODE REVIEW

**Comment by RufusJWB** [comment]
@NoMoreFood Do you have a profile at chocolatey? I'd need to make you the maintainer of the package, otherwise you can't push.

**Comment by NoMoreFood** [comment]
I just created a profile https://community.chocolatey.org/profiles/NoMoreFood that is affiliated with berns@uwalumni.com

**Comment by NoMoreFood** [comment]
Sounds good!  I'll be in touch.

**Comment by RufusJWB** [comment]
Hi @NoMoreFood ! Are you planning to release a new version of putty-cac so that we can finalize the hand-over of the chocolatey package to you?

**Comment by NoMoreFood** [comment]
@RufusJWB Yes, been meaning to touch base with you.  Set of files is in https://github.com/NoMoreFood/putty-cac/tree/master/packager/chocolatey.  I can touch check, but I believe they've been updated to support the updated chocolatey release for 0.78.

**Comment by RufusJWB** [comment]
Hi @NoMoreFood . What would be our next step now? Should we set up a Teams meeting and go through the steps to update chocolatey together?

**Comment by NoMoreFood** [comment]
@RufusJWB  Sure. Do you have time this coming Friday?

**Pull request merged**
