### PR TITLE
output hash information in sha256sum formart

### PR DESCRIPTION
**Pull request by MaxPeal**
so it can be checked with:
sha256sum -c puttycac-hash.sha256

### CODE REVIEW

**Comment by NoMoreFood** [comment]
Is something missing?  For example, the new environment you specified isn't actually used anywhere.  When I run the snippet, all it does it appear to produce output to the console similar to the following:

```
b948526d8304d7c72a8b2f89051853e45be4b3c85cae5520e7b86b5e444dc300 *x64\pageant.exe
d63c577baaf23bd9f636fd23ab8c6e98cd8220b3e81d27eced99cb417bbce4ca *x64\plink.exe
45e6a46e522b9215c50fe4932f511f3c8b34a5318f65e54bb1b91b65ddb4db21 *x64\pscp.exe
035cdc2a226a854c71e7670720077a3e588ca33d743d8d23ce3f67cba008580d *x64\psftp.exe
0bc3b29a2b719b1cade4423abd89e78cdae962c4d0b5d48f60e0fdd00d182f0b *x64\putty.exe
85932f89dc2aa0f1bcdce34276f6e1cbe97a9dee42ed6d61750e8fb1114d67df *x64\puttygen.exe
89eace169d0391049740afcad61feec1a4ffd18ab7e831092b5e20671ea98867 *x64\puttytel.exe
6bb2328aea9afeaaeedfe65f56a673caa2dcd591a2345afc623bb34b877f3610 *x86\pageant.exe
8ec98a90ad381cc5e88b759d15b85c55ac7ddb049dfd16575dcbbb4e14e5d371 *x86\plink.exe
e50fe6db42177fd635d2ad04ced07f4288a437f71b7b36557228c73c43a158e6 *x86\pscp.exe
25c1e0ae754850ff8710bcb0d4429feb155762f61e17e0fb56e733365b28f6d9 *x86\psftp.exe
0e9d3671e4d1708fda0dac402beb8fb0594a9a801b8a5b0e7d3f6fcd0af03997 *x86\putty.exe
db7856580da28062e67b34d742608a66f81eaedb3afdbd0078e1c7f588bd9c3d *x86\puttygen.exe
81ebbf06ff6bf4957df9eea9070e0f2be7d5a64be3436e02513d96875464cdbb *x86\puttytel.exe
7267952d6e6d3e34b7d8119da5721332189e55b95c40e3c7e2fa332ca83f1216 *puttycac-0.74-installer.msi
e47526db93933b961c0d5da59112aed28504b77c47debd0921252daf0655bea2 *puttycac-0.74.zip
2aedf0fc5b97ac524f2bc5b150c4d4b963d588c65f7bde92d0f4b55d895700e7 *puttycac-64bit-0.74-installer.msi
6c295eb656a1d95c9c1bbd52ef4e5a638adb7f3ecc59b23abb1dc940cfb79e4a *puttycac-64bit-0.74.zip
```

**Comment by MaxPeal** [comment]
@NoMoreFood yes some parts are missing, sorry.
i update the PR, in the next 1/2 hour

**Comment by MaxPeal** [comment]
@NoMoreFood so PR ready to test form you side.
if its work and so i will squash the PR if you wish

**Comment by NoMoreFood** [comment]
Thanks, can you describe what you're doing overall in this PR and why you're doing it?

**Comment by karlg100** [comment]
any chance this solves FIPS compatibility with RHEL8?  Right now, fails because it passes ssh-rsa as the key type, which is disabled in RHLE8 FIPS mode.

**Comment by NoMoreFood** [comment]
Try using Pageant and see if that works.

**Comment by karlg100** [comment]
It does not.  I realized looking at the patches, this merge is probably not related.  I’ll open a new issue.

Karl Grindley

**Comment by NoMoreFood** [comment]
Closing due to no response with no clear intent of what this change is doing.

**Pull request closed without merging**
